[package]
name = "demo"
version = "0.1.0"
edition = "2021"
resolver = "1"

[dependencies.plotters-dioxus]
path = "../plotters-dioxus"

[dependencies]
dioxus = "0.4.3"
dioxus-desktop = "0.4.3"
plotters = "0.3.5"
rand = "0.8.3"
rand_distr = "0.4.3"
rand_xorshift = "0.3.0"