[package]
name = "demo"
version = "0.1.0"
edition = "2021"

[dependencies.backend-dioxus]
path = "../backend-dioxus"

[dependencies]
dioxus = "0.4.3"
dioxus-desktop = "0.4.3"
plotters = { version = "0.3", features = ["histogram"]}